version: "3.8"

services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    tty: true
    # volumes:
    #   - ./api-gateway:/app        # Código fica visível e editável localmente
    working_dir: /app
    # command: ["go", "run", "."]
    ports:
      - 8000:8000